sudo: required

services:
  - docker

before_install:
  - docker build -t ajaybojedla/hello-world-python .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajaybojedla/hello-world-python



